#!/usr/bin/env python3

import sys
import urllib3
import re

def main(argv):
    http = urllib3.PoolManager()
    query = ' '.join(argv[1:])
    r = http.request('GET', 'https://tpb.party/search/{}/0/99/0'.format(query))

    titles = re.findall(r"(?<=title\=\"Details for )[^\"]*", str(r.data))
    urls = re.findall(r"(?<=href=\")magnet:[^\"]*", str(r.data))
    tus = list(zip(titles, urls))
    for i in range(len(tus)):
        print("{}:   {}".format(tus[i][0], tus[i][1]))

if __name__ == "__main__":
    main(sys.argv)

